### ISSUE TITLE
installation on windows does not work because on pip installation it trys to compile c-code with make

### ISSUE THREAD

**Issue by berndhahnebach** [centreborelli/srtm4#11]
and make is not available on std. windows

**Comment by berndhahnebach** [comment]
Someone around who has successfully build it on windows? libtiff is needed too. We are struggeling because there is neiter a CMake nor a .sln file

**Comment by mnhrdt** [comment]
This should work on windows under WSL and an appropriate build-tools installation.  Unfortunately it is not tested on CI.  Feel free to add it to the tests if you manage to make it work.
