### ISSUE TITLE
'tiffio.h' file not found on Mac

### ISSUE THREAD

**Issue by diego-gris** [centreborelli/srtm4#18]
src/srtm4.c:9:10: fatal error: 'tiffio.h' file not found
  #include <tiffio.h>
           ^~~~~~~~~~

I installed libtiff via homebrew: brew install libtiff, but I am getting this erroe when running pip install srtm4
Any suggestions?

**Comment by mnhrdt** [comment]
try setting the following variables on your shell:

    export C_INCLUDE_PATH=/usr/local/include
    export LIBRARY_PATH=/usr/local/lib

Explanation: some combinations of homebrew/compiler install C libraries in folders that are not  seen by the compiler by default.  Set these variables to wherever you want the compiler to find the files.
