### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by daviddemeij** [centreborelli/srtm4#21]
SRTM4 is currently returning a 404 error:
```
ConnectionError: Response code 404 received for url https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_36_01.zip
```

When I try to go to https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_36_01.zip I get:
> Sorry, the page you are looking for could not be found.

Are these permanently offline or will they go back online soon?

**Comment by mnhrdt** [comment]
Yes, the cgiar urls are broken right now. I don't know  whether this is a permanent or temporary problem.

**Comment by mnhrdt** [comment]
> Are there any mirrors?

If you find one, it's easy to replace here: https://github.com/centreborelli/srtm4/blob/master/srtm4/download.py#L20

There are many mirrors of these data, but I couldn't find any that allows anonymous downloads.

By the way, I contacted CGIAR and they acknowledge the problem, but they do not give a timeline to fix it.  If it lasts more than a day, we can try to host the database temporarily elsewhere.  The whole collection of tiles at 90m should be about 20gb.

**Comment by mnhrdt** [comment]
Today the CGIAR service seems to be restored. Just in case, it is still useful to recall the USGS url by @tonzowonzo on his PR https://github.com/centreborelli/srtm4/pull/22 :

https://e4ftl01.cr.usgs.gov//DP133/SRTM/SRTMGL1.003/2000.02.11

(notice however that the filenames for the tiles in this site follow a different naming scheme, so the URL cannot be replaced as-is).

**Comment by fnands** [comment]
@mnhrdt , the usgs server requires you to login, while CGIAR allows for anonymous downloads right?

**Comment by mnhrdt** [comment]
Yes.  And this may be a good thing in case somebody--or some organisation--wants to make heavy use of the tiles without being afraid to strain the CGIAR servers.  I'm a bit scared they will close the anonymous service if it becomes too popular.  It would be nice to have optional support for non-anonymous downloads from USGS with a user-specific api key.

**Comment by mnhrdt** [comment]
It seems to be working now.
